# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d623867812e625d9a168776a027e5cb7da6c39c45cf4471385007c393dc2080ecebfa1f285826fda0f2f13bb173fd8bda721eedcc843ba440e050cd0f22a9119

test:
  secret_key_base: 8ed886e47426ee307e0bf580e36af1c063ba00466afa42ec40df175b2d94b9e98bc609ae4a1012b1c994a8b11cdb1c992e62e663424b85a0155923a745b99e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
